dist: xenial
language: python
python:
- '3.7'
install: pip install tox-travis
script: tox
deploy:
  provider: pypi
  user: __token__
  on:
    tags: true
    distributions: sdist bdist_wheel
  password:
    secure: DSwJsbYir1RIC2iOApbnfF5tQiyXHFSJ7mmvMbZ+yHSo6OjFsmL7LJnfPJF0M8mfUo/UPdlYff93EBbqR6KsgH0eRgmXS31jepjJga1vQG3jViV4tbbhBAfTIuehP2yogD0RDw/NCfbW/Guu3pHoIiMyl0UoIhwLnQno0gKBt0g8qoNmfwGFLPQl+Yb9kpSgDN8/3ZkJ/MOJytyBuM0mzcrtaCTgLRSZg+xx0uq+qzfV6dwlomXzM9uS1uWhBoX+XK0OsOLCCKEonLSrqB69cQ29w4c1DuFfA1DuG5WeXZdLu6tCvpJ4Bh6AR0p06eP9uyPVDZV0NvPc00cXwEJkmrED1EyDJfK33QbkuTIvpZkXaT5w1bsRXlh6tkj0MxF25SjoASiAhIjqiQhuna25DMnx1Hp0x+jtlBcOv9fmdtLHSqk9BQ5RS3AosGMt8VaH3eJ9EusrJ0k3ez/QW80APDge98UAQcuv/Lvv1tlqENMltnuyjxXmVxnXYxqIiOdSBFBpDZh0JQVZklFGOItd3PJf5LwKfp1uC6t/5XI9/0m5+JDEdAABZ7X1EZ/X+nB/FohQuSaWWAfCP+6YSdVmIoDc19HXuf9aAGkoH5BVX8YzNs39TT8Z4bPRx8tKrF/APd7WpUgqZNqNIpnRjKhacAyNtdeMS71DNqh8Vym2w00=
