site_name: Model Insertion Checker (MIC)
nav:
  - Home: index.md
  - Available commands: usage.md
  - Configure: configure.md
  - Add model: usage-add-model.md
  - FAQ: faq.md

theme: 
  name: material
  logo: 'logo.png'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
